#include "../include/mapreduce.h"
#include <math.h>
#include <stdio.h>
#include <unistd.h>

#define NUM_DIGITS 10

int main(int argc, char *argv[]) {

  if (argc < 4) {
    printf("Less number of arguments.\n");
    printf("./mapreduce #mappers #reducers inputFile\n");
    exit(0);
  }

  // ###### DO NOT REMOVE ######
  int nMappers = strtol(argv[1], NULL, 10);
  int nReducers = strtol(argv[2], NULL, 10);
  char *inputFile = argv[3];

  // status variable for pids
  int status;
  // string that represents the id arg for mapper and reducer, allocates 10
  // bytes which means we can have max 9 digits for our id, which I assume
  // is more than enough
  char arg[NUM_DIGITS];

  // ###### DO NOT REMOVE ######
  bookeepingCode();

  // ###### DO NOT REMOVE ######
  pid_t pid = fork();
  if (pid == 0) {
    // send chunks of data to the mappers in RR fashion
    sendChunkData(inputFile, nMappers);
    exit(0);
  }
  sleep(1);

  // To do
  // spawn mappers processes and run 'mapper' executable using exec
  for (int i = 0; i < nMappers; i++) {
    pid = fork();
    if (pid == -1) {
      printf("error forking\n");
      return -1;
    }
    if (pid == 0) {
      sprintf(arg, "%d", i + 1);
      execl("mapper", "mapper", arg, NULL);
    }
  }

  // To do
  // wait for all children to complete execution
  while (wait(&status) > 0)
    ;

  // ###### DO NOT REMOVE ######
  // shuffle sends the word.txt files generated by mapper
  // to reducer based on a hash function
  pid = fork();
  if (pid == 0) {
    shuffle(nMappers, nReducers);
    exit(0);
  }
  sleep(1);

  // To do
  // spawn reducer processes and run 'reducer' executable using exec
  for (int i = 0; i < nReducers; i++) {
    pid = fork();
    if (pid == -1) {
      printf("error forking\n");
      return -1;
    }
    if (pid == 0) {
      sprintf(arg, "%d", i + 1);
      execl("reducer", "reducer", arg, NULL);
    }
  }

  // To do
  // wait for all children to complete execution
  while (wait(&status) > 0)
    ;

  return 0;
}
