CC = gcc
CFLAGS = -g -Wall
LDFLAGS = -lm
OBJS = main.o apple.o

myprog: ${OBJS}
	${CC} ${LDFLAGS} ${OBJS} -o myprog
main.o: main.c apple.h
	${CC} ${CFLAGS} -c main.c
apple.o: apple.c apple.h
	${CC} ${CFLAGS} -c apple.c
clean:
	rm -f *.o myprog

